// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHII_E8jEaqsEe3N-DoI9Ib40pLLP1QB8',
    appId: '1:382633637335:web:374548588bb69d3fcf8792',
    messagingSenderId: '382633637335',
    projectId: 'toko-koreku',
    authDomain: 'toko-koreku.firebaseapp.com',
    storageBucket: 'toko-koreku.firebasestorage.app',
    measurementId: 'G-2ES9DENFDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFDPJhXebxoL4jcGzuGkcuD4v8ZgirFA',
    appId: '1:382633637335:android:910163cff1ba046fcf8792',
    messagingSenderId: '382633637335',
    projectId: 'toko-koreku',
    storageBucket: 'toko-koreku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnZNL_gj063iO6lP8QVQ_fCqa3Fdu_7s',
    appId: '1:382633637335:ios:98b74636643c77e8cf8792',
    messagingSenderId: '382633637335',
    projectId: 'toko-koreku',
    storageBucket: 'toko-koreku.firebasestorage.app',
    iosClientId: '382633637335-j3k7opk2v4hpk8tj9tag6cp4ir5qjuv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokoKoreku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnZNL_gj063iO6lP8QVQ_fCqa3Fdu_7s',
    appId: '1:382633637335:ios:98b74636643c77e8cf8792',
    messagingSenderId: '382633637335',
    projectId: 'toko-koreku',
    storageBucket: 'toko-koreku.firebasestorage.app',
    iosClientId: '382633637335-j3k7opk2v4hpk8tj9tag6cp4ir5qjuv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokoKoreku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHII_E8jEaqsEe3N-DoI9Ib40pLLP1QB8',
    appId: '1:382633637335:web:d7964a8d6bad6f0acf8792',
    messagingSenderId: '382633637335',
    projectId: 'toko-koreku',
    authDomain: 'toko-koreku.firebaseapp.com',
    storageBucket: 'toko-koreku.firebasestorage.app',
    measurementId: 'G-BML16Z9XPX',
  );

}